ch1/chatting/urls.py
from django.conf.urls import patterns, url
from chatting import views

urlpatterns = patterns('',
    url(r'^$',views.Index.as_view(),name="index"),
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^selectBtn/$',views.Team_selectBtn.as_view(),name='selectBtn'),
    url(r'^teamCreate/$',views.Team_create.as_view(),name='teamCreate'),
    url(r'^teamEnter/$',views.Team_enter, name='teamEnter'),
    url(r'^team/(?P<team_name>\w+)/$',views.Chat.as_view(),name='team'),
)

ch1/slang/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^slang/', include('chatting.urls', namespace='slang')),
]

ch1/chatting/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

class Member(AbstractBaseUser):
    """
    Custom user class.
    """
    username = models.CharField(max_length=30,unique=True,)
    email = models.EmailField('email address', unique=True, db_index=True)
    joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'username'
    
    def __str__(self):
        return self.username

class Team(models.Model):
    team_name = models.CharField(max_length = 20)
    username = models.ManyToManyField(Member)
    
    def __str__(self):
        return self.team_name
    
class File(models.Model):
    file_name = models.CharField(max_length = 100)
    file_size = models.IntegerField(default = 0)
    file_data = models.CharField(max_length = 30)
    team_id = models.ForeignKey(Team)
    member_id = models.ForeignKey(Member)
    
    def __str__(self):
        return self.file_name

ch1/chatting/forms/authentication.py
from django import forms

class AuthenticationForm(forms.Form):
    """
    Login form
    """
    username = forms.CharField(widget=forms.widgets.TextInput)
    password = forms.CharField(widget=forms.widgets.PasswordInput)

    class Meta:
        fields = ['username', 'password']

ch1/chatting/forms/register.py
from django import forms
from chatting.models import Member

class RegistrationForm(forms.ModelForm):
    """
    Form for registering a new account.
    """
    username = forms.CharField(widget=forms.widgets.TextInput,label="Username")
    email = forms.EmailField(widget=forms.widgets.TextInput,label="Email")
    password1 = forms.CharField(widget=forms.widgets.PasswordInput,
                                label="Password")
    password2 = forms.CharField(widget=forms.widgets.PasswordInput,
                                label="Password (again)")

    class Meta:
        model = Member
        fields = ['username','email', 'password1', 'password2']

    def clean(self):
        """
        Verifies that the values entered into the password fields match

        NOTE: Errors here will appear in ``non_field_errors()`` because it applies to more than one field.
        """
        cleaned_data = super(RegistrationForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return self.cleaned_data

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

ch1/chatting/views.py
from django.shortcuts import render_to_response, redirect, render
from django.template import RequestContext
from django.views.generic import ListView, View, TemplateView
from django.contrib.auth import login as django_login, authenticate, logout as django_logout
from django.views.decorators.csrf import csrf_exempt
from chatting.forms import AuthenticationForm, RegistrationForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect,HttpResponse
from chatting.models import Member,Team
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect,requires_csrf_token
import json
from django.contrib.sessions.models import Session
from django.utils import timezone
from django import template


class Index(TemplateView):
    template_name = "chatting/index.html"
    
@csrf_exempt
def login(request):
    """
    Log in view
    """
    if request.method == 'POST' and request.is_ajax():
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST['username'], password=request.POST['password'])
            m = Member.objects.get(username=request.POST['username'])
            if user is not None:
                if user.is_active:
                    request.session['member_id']=m.id
                    request.session['member_name']=m.username
                    django_login(request, user)
                    return HttpResponse(json.dumps({'code': '200'}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({'code': '100'}), content_type="application/json")
    else:
        form = AuthenticationForm()
    return render_to_response('chatting/login.html', {
        'form': form,
    }, context_instance=RequestContext(request))


@csrf_exempt
def Team_enter(request):
    if request.method == 'POST':
        name = request.POST['teamName']
        try:
            checkName = Team.objects.get(team_name=name)
        except:
            return HttpResponse(json.dumps({'code':'100'}),content_type="application/json")
        else:
            return HttpResponse(json.dumps({'code':'200'}),content_type="application/json")
    else:
        return render_to_response('team/enter.html',context_instance=RequestContext(request))
        
@csrf_exempt
def register(request):
    """
    User registration view.
    """
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(reverse('slang:login'))
    else:
        form = RegistrationForm()
    return render_to_response('chatting/register.html', {
        'form': form,
    }, context_instance=RequestContext(request))

def logout(request):
    """
    Log out view
    """
    django_logout(request)
    return redirect(reverse('slang:register'))

class Team_create(TemplateView):
    template_name = "team/create.html"
    def post(self,request):
        name = request.POST['teamName']
        new_team = Team(team_name=name)
        new_team.save()
        return redirect(reverse('slang:teamEnter'));


        
class Chat(TemplateView):
    template_name = "team/chat.html"
    
class Team_selectBtn(TemplateView):
    template_name = "team/selectBtn.html"

ch1/chatting/templates/chatting/Login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script>
    function checkForm(){
        var val = $('form[name="LoginForm"]').serialize();
        $.ajax({
            type:'POST',
            data:val,
            success:function(data){
                if(data.code == '200'){
                    $('#error').html('<p>logined</p>');
                    parent.right();  
                }
                else{
                    $('#error').html('<p>ID나 PW가 일치하지 않습니다.</p>');
                    var pw=$('input[name="password"]').val("");
                }
            }
        });
        
        return false;
            
        }
    /*$(document).ready(function(){
      $('form').attr("disabled",false).attr("readonly",fasle);
        });*/
</script>
<body>
   
   <div id="error"></div>
 
    <form onsubmit="return checkForm()" class="form-horizontal" name="LoginForm" method="post" disabled>
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
        {% endif %}
        <div class="control-group">
            <label class="control-label" for="username">Username</label>
            <div class="controls">
                {{form.username}}
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="password">Password</label>
            <div class="controls">
                {{form.password}}
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Login</button>
            </div>
        </div>
        </form>
       
</body>
</html>

ch1/chatting/templates/chatting/Signup.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#tt').click(function(){
                parent.right();
});   
        });
    </script>
</head>
<body>
    <form action="{% url 'slang:Signup' %}" method="post">
       {% csrf_token %}
        {{form.username}}
        {{form.password}}
        {{form.email}}
        <button type="submit" id="tt">Signup</button>
    </form>  
</body>
</html>

ch1/chatting/templates/chatting/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cloud Carousel Demo</title>
 
    <!-- You can load the jQuery library from the Google Content Network.
    Probably better than from your own server. -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
     
    <!-- Load the CloudCarousel JavaScript file -->
    <script src="{% static 'js/cloud-carousel.1.0.5.js' %}"></script>
     
    <script>
    $(document).ready(function(){
        
        $('.cloudcarousel').wrap('<div class="inWrap"></div>');
        
        //$('.inWrap').css({'width':'100%','height':'100%','position':'relative','background-color':'transparent','opacity':'0.5'});
    	// This initialises carousels on the container elements specified, in this case, carousel1.
    	$("#carousel1").CloudCarousel(		
    		{			
    			xPos: 350,
    			yPos: 202,
                mouseWheel:false,
    			buttonLeft: $("#left-but"),
    			buttonRight: $("#right-but"),
                buttontRight: $('#tRight-but'),
    			altBox: $("#alt-text"),
    			titleBox: $("#title-text"),
                FPS:90
    		}
    	);
     
    
    });
    function left(){
        $('#left-but').trigger('mouseup');  
    }
    function right(){
        $('#right-but').trigger('mouseup');  
    }
    function twoRight(){
        $('#tRight-but').trigger('mouseup');
    }
         $('iframe').contents().find('form').each(function(){
                
                $(this).attr("disabled",true).find('button').attr("disabled",true);
            });
    </script>
 <style>
     iframe{
         width:250px;
         height: 250px;
     }
     
    </style>
    <style>
    
        tt
    </style>
</head>
    <body>
    	<!-- This is the container for the carousel. -->
        <div id = "carousel1" style="width:1000px; height:502px; margin:0 auto;background:#fff;overflow:scroll;">            
            <!-- All images with class of "cloudcarousel" will be turned into carousel items -->
            <!-- You can place links around these images -->
           
      
              <iframe  class="cloudcarousel" name="ifm" src="{% url 'slang:login' %}" style="border-radius:50px 50px;" frameborder="1"  scrolling="no" marginheight="10" marginwidth="10">
              </iframe>
              
            
              <iframe class="cloudcarousel" name="ifm" src="{% url 'slang:register' %}" style="border-radius:50px 50px;" frameborder="1" scrolling="no" marginheight="10" marginwidth="10">
              </iframe>
              dd
          
           
              <iframe class="cloudcarousel" name="ifm" src="{% url 'slang:teamCreate' %}" style="border-radius:50px 50px; " frameborder="1"  scrolling="no" marginheight="10" marginwidth="10">
              </iframe>
                 
              <iframe class="cloudcarousel" name="ifm" src="{% url 'slang:teamEnter' %}" style="border-radius:50px 50px; " frameborder="1"  scrolling="no" marginheight="10" marginwidth="10" >
              </iframe>
                 
              <iframe class="cloudcarousel" name="ifm" src="{% url 'slang:selectBtn' %}" style="border-radius:50px 50px;" frameborder="1"  scrolling="no" marginheight="10" marginwidth="10">
              </iframe>
              
        </div>
        
        <!-- Define left and right buttons. -->
        <div style="background-color:#fff">
            <input id="left-but"   value="Left">
            <input id="right-but" value="Right">
            <input id="tRight-but" type="hidden">
        <div>
<p id="dd">ddd</p>
        <!-- Define elements to accept the alt and title text from the images. -->
        <p id="title-text"></p>
        <p id="alt-text"></p>
      <div id="allDiv"></div>
    </body>
</html>

ch1/chatting/templates/chatting/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<style>
    *{
        margin:0;
        padding:0;
    }
     
</style>
<body style="position:absolute; width:100%; height:100%; opacity:0.8;">
    <!--{% if user.is_authenticated %}
    <p>logined</p>
    {% endif %}-->
    
    <div style=" text-align:center; top:100px; position:relative;">
        <h2 style="color:white;">Signup</h2>
    </div>
    <form method="post" action="{% url 'slang:register' %}" disabled>
       {% csrf_token %}
        <div>
            {{form.username.label}}
            {{form.username}}
        </div>
        <div>
            {{form.email.label}}
            {{form.email}}
        </div>
        <div>
            {{form.password1.label}}
            {{form.password1}}
        </div>
        <div>
            {{form.password2.label}}
            {{form.password2}}
        </div>
        <button type="submit">register</button>
    </form>
</body>
</html>

ch1/chatting/templates/team/chat.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>slang</title>

</head>

<body>
    {% if users %}
    <ul class="user-list">
        {% for user in users %}
        <li>{{ user }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
    <div style=" text-align:center; top:100px; position:relative;">
        <h2 style="color:white;">chat</h2>
    </div>
    <div>
       {% for request.session.member_name %}
        {{request.session.member_name}}
        {% endfor %}
        <h1>{{team_name}}</h1>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="teamName" placeholder="team_name" />
            <button class="btn btn-primary" name="create">채팅입력</button>
        </form>
    </div>
</body>

</html>

ch1/chatting/templates/team/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
	   <meta charset="utf-8">
	   <meta http-equiv="X-UA-Compatible" content="IE=edge">
	   <meta name="viewport" content="width=device-width, initial-scale=1">
	   <title>slang</title>
	   <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div style=" text-align:center; top:100px; position:relative;">
        <h2 style="color:white;">create</h2>
    </div>
        <div > 
            <form method="post" disabled >
                {% csrf_token %}
                <input type="text" name="teamName" placeholder="team_name"/>
                <button class="btn btn-primary" name="create" disabled>개설</button>
            </form>
        </div>
    </body>
</html>

ch1/chatting/templates/team/enter.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>slang</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<script>
     function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');


        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
    $(function() {
        
       

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    });

    function checkTeam() {
        var val = $('form[name="teamForm"]').serialize();
        $.ajax({
            type: 'POST',
            data: val,
            success: function(data) {
                if (data.code == '200') {
                    alert(1);
                    var teamName = $('input[name="teamName"]').val();
                    window.parent.location.href = '/slang/team/' + teamName;

                } else {
                    alert('팀이 존재하지 않습니다.');
                }
            }
        });

        return false;

    }

</script>

<body>
    <div style=" text-align:center; top:100px; position:relative;">
        <h2 style="color:white;">enter</h2>
    </div>
    <div>
        <form method="post" name="teamForm" onsubmit="return checkTeam()">
            {% csrf_token %}

            <input type="text" name="teamName" placeholder="team_name" />
            <button name="enter">입장</button>
        </form>
    </div>
</body>

</html>

ch1/chatting/templates/team/selectBtn.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#enter').click(function(){
                parent.right();    
            });      
            $('#create').click(function(){
                parent.twoRight(); 
            });
        });
    </script>
</head>
<body>
   <div style=" text-align:center; top:100px; position:relative;">
        <h2 style="color:white;">selectBtn</h2>
    </div>
   <form disabled style="display:none;">
    <button id="enter">enter</button>
    <button id="create">create</button>
    </form>
</body>
</html>